package videoprocessing;

public enum VideoProcessorError {
    VIDEO_PROCESSOR_SUCCESS,
    VIDEO_PROCESSOR_NOT_VIDEO_ERROR,
    VIDEO_PROCESSOR_DEPTH_MOTION_ERROR,
    VIDEO_PROCESSOR_OUT_OF_BOUNDS_ERROR,
    VIDEO_PROCESSOR_TEMP_ERROR
}
